version: '3'

services:
  telegram-trivia-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    volumes:
      - /tmp/dockervol:/app/chatdbs/
