name: telegram-trivia-chatbot build and run

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: telegram

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker Compose
      run: | 
        echo "TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }}" >> .env
        docker-compose up --build -d
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}